### ISSUE TITLE
Failed to import the library via SwiftPM in Xcode 12.4 

### ISSUE THREAD

**Issue by starrynight** [htacg/SwLibTidy#1]
Attempted to import this library in SwiftPM, Xcode 12.4, macOS 11.4 without success. 
dependancy is specified as 
```swift
    dependencies: [
        .package(
            name: "SwLibTidy",
            url: "https://github.com/htacg/SwLibTidy.git",
            .branch("master")
        )
    ],
```
The error message is  
Failed to parse the manifest file
Detailed user info is Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Error Domain=NSCocoaErrorDomain Code=260 "The file “version.txt” couldn’t be opened because there is no such file."

I think 
`CONTENTS = try String(contentsOfFile: VERSION_FILE).components(separatedBy: "\n")` caused the issue as SPM didn't have the chance to copy the cLibTidy sources to local directory when version.txt is unavailable

**Comment by balthisar** [comment]
Do you know if SwiftPM is fetching the the git submodule? It _does_ fetch the submodule for me automatically when using on the command line, meaning that "version.txt" exists. I'll see if I can figure out how to make it work directly with Xcode, unless you already know a solution?

**Comment by starrynight** [comment]
SwiftPM failed at package resolve phase, didn't fetch anything. I repeated it at command line with same error. I can only presume that it worked for you because there is Package.resolved in your project folder already. But for an initial setup, the current Package.swfit probably is not going to work in either Xcode or command line mode.

**Comment by balthisar** [comment]
It seems that Xcode doesn't pull the submodule, whereas working on the command line does. I can fix this by targeting a version and not building the version dynamically, instead of targeting a branch and building version dynamically. I'd rather not do this, because it makes it easy to decouple the stated version number from the actual version number.

I've posted a support request on the Swift mailing list. In the meantime, working with this is a local package instead of a remote package also works in Xcode.

Hope to resolve this quickly.

**Comment by balthisar** [comment]
@starrynight, try it from the `debug_xcode` branch, if you would. It seems like supplying a default is good enough for resolving the manifest, and will be built properly once the submodule is pulled. If it works for you, I'll merge the change back into master.

Thanks.

**Comment by starrynight** [comment]
Yes, the debug_xcode branch does work for me. I agree a good enough default serves the purpose. 
Thanks a lot for bringing this to the swift world!

**Comment by balthisar** [comment]
Merged. Thanks.
